bluesky/databroker

- .travis.yml
- conda-recipe/meta.yaml
- databroker/__init__.py
- databroker/databroker.py
- databroker/tests/test_broker.py
- databroker/tests/test_broker_search.py
This provides more flexibility at no cost.  We can, at any time, extend
the functionality of the databroker to handle new argument types to the
db[] notation by using singledispatch
Blocking Issues
----------------
> Use single dispatch for databroker getitem

- conda-recipe/meta.yaml
conda build master is now using a two-pass jinja system which means
that environ should be accessed via .get() instead of [] if you want
to access GIT_* variables.
> BLD: Use .get() instead of directly accessing env

- databroker/__init__.py
- databroker/databroker.py
- databroker/tests/test_broker.py
We documented this but never actually wrote it.
Having trouble running tests locally due to pip problems + pymongo thrashing.
> ENH: Implement a drop-in replacement for RunEngine Document Dispatcher.

- .travis.yml
- conda-recipe/meta.yaml
- databroker/databroker.py
- databroker/examples/sample_data/step_scan.py
- databroker/pims_readers.py
- databroker/tests/test_broker.py
- Any fields not found in an event will be looked for in
its descriptor's configuration, then in start, then in stop.
- This passes the existing tests, which use documents that have
no 'configuration' field at all. More tests coming.
- A dependency on cytoolz or toolz (same API) is introduced.
> ENH: Search for fields in event, descriptor, start, stop.

- databroker/__init__.py
- databroker/databroker.py
- databroker/tests/test_broker.py
- doc/source/fetching.rst
A primary use case for the recently-introduced `restream` (formerly called `stream`) is a list comprehension:
```python
docs = restream(header)  # a generator
[some_callback(name, doc) for name, doc in docs]
```
This PR introduces a convenience function to make that easy.
```python
process(header, some_callback)
```
Perhaps we should accept a list of callbacks or, as in bluesky, the dict `{'all': [...], 'start': [...], ...}` routing documents by type. But I think it's best to keep it simple here. If users need to use multiple callbacks, they can always roll their own dispatching function or use `CallbackBase`.
> ENH: Add process; rename stream -> restream (with back-compat)

- databroker/databroker.py
- databroker/pims_readers.py
- databroker/tests/test_broker.py
- All get* functions also accept an optional `handler_overrides` argument
that maps data_keys to handlers, overriding the lookup based on spec name
- The override only affects a single call.
- get_table and get_images now accept optional `handler_registry` argument
(get_events already supported this)
Use Case:
- Debugging by say using a handler that returns raw resource/datum dicts
- Swapping lazy/non-lazy handlers as needed
- Suppose we collect data and then realize we want information that is not
in the Events but *is* in the files (e.g., timestamps in HDF5 image files).
This gives us a recourse: registing a custom handler that uses the same
resource and datum documents but returns totally different data (the
timestamps instead of the images). Obviously it's better to capture everything …
> ENH: Allow hanlder override by data key.

- databroker/core.py
At beamlines, I find myself using this pattern a lot:
```python3
events = [ev for ev in get_events(hdr, ['x']) if 'x' in ev.data]  # filter out events that don't have 'x'
```
I think `get_events` should be filtering out events that are completely empty.
I've been sitting on this awhile, because this is not a decision we should thrash on, but I've become pretty convinced that the upside outweighs in the downside in the use cases I see. Thoughts?
> API: Skip empty events.

- databroker/broker.py
- databroker/core.py
- databroker/tests/test_broker.py
The databroker can query the EPICS Archiver Appliance and return the results as documents that are compatible with those from metadatastore. (A simulated descriptor and event stream are written.)
This is implemented using a new "plugin" capability that could also be used to integrate other external sources without changing the databroker code. So, individual beamlines can customized their databrokers. For example, we might programmatically access the Olog through databroker as well.
Tested successfully using LIX archiver and CSX metadataservice:
```python3
import metadatastore.commands, filestore.api
import databroker
plugin = databroker.broker.ArchiverPlugin('http://xf16idc-ca.cs.nsls2.local:17668/', 'US/Eastern')
db = databroker.Broker(metadatastore.commands, filestore.api, {'pvs': …
```
> At long last: archiver appliance integration

- databroker/broker.py
- databroker/core.py
- databroker/tests/test_broker.py
- databroker/tests/test_example_hdf_io.py
Motivation:
* new `name` arg: Bluesky will be producing more asynchronous event streams. We want `get_table` to continue to "just give me my data".
* fill: Users commonly experience slow performance unnecessarily because they don't know to set `fill=False`. Also, this makes `restream` and `process` compatible with bluesky callbacks, which expect the unfilled documents emitted by the RunEngine.
See the added docstrings for details. Tests pass but coverage on new features is low. Careful review would be appreciated. Tests will improve when someone has the time to generate test data from bluesky itself, as has been proposed elsewhere.
> API: Set fill=False by default; add 'name' filtering arg.

- .travis.yml
- conda-recipe/meta.yaml
dependency to the meta.yaml so that the `broker.py` module is importable
> BLD: Add requests to the recipe requirements

- databroker/broker.py
Exposing the full-text search added in NSLS-II/metadatastore#215 via the broker. Demo:
```python
In [5]: len(db('linear_motor'))
Out[5]: 4
```
> ENH: Add support for full-text queries using syntax `db('keyword')`

- databroker/broker.py
- databroker/core.py
- doc/source/api_changes.rst
- doc/source/index.rst
Change the name of the 5th positional arg in `get_table` from `name` ->
'stream_name`.  The new argname is clearer and aligns with the naming
convention used in LiveTable.
> API: change arg name from name -> stream_name

- databroker/broker.py
- databroker/tests/test_broker.py
This improves coverage of Broker and belatedly puts docstrings on the alias-related methods.
> Add more tests

- databroker/broker.py
This was missed when the stream_name API was change.
> FIX: use default stream name in get_resource_uids

- databroker/scripts/fs_rename
Given a runstart, rename all of the files belonging to all of the
resources.
If the root is not set on the resource you _must_ use preshift to move
some of the directory level into 'root' to be replaced.
Use of this tool is strongly discouraged.
attn @heroux
> MNT: add a cli tool for renaming files

- databroker/broker.py
- databroker/core.py
```python
import databroker
import bluesky
import bluesky.plans as bp
import datetime
from bluesky.examples import det
import portable_mds.sqlite.mds as pmsm
mds = pmsm.MDS({'directory': '/tmp/pmds', 'timezone': 'US/Eastern'})
db = databroker.Broker(mds, None)
class TimeFaker:
def __init__(self, mds, start_time, step):
self.start_time = start_time.timestamp()
self.step = step
self.counter = 0
self.mds = mds
self.last_uid = None
def insert(self, name, doc):
if name == 'start':
self.counter = 0
self.last_uid = doc['uid']
if 'time' in doc:
doc['time'] = self.start_time + self.counter * self.step
self.counter += 1
self.mds.insert(name, doc)
start_time = datetime.datetime(2016, 3, 12, 23, 5)
tf = TimeFaker(db.mds, start_time, 5*60)
RE = bluesky.RunEngine()
RE.subscribe('all', tf.insert) …
```
> Fix timezones

- databroker/broker.py
- databroker/tests/test_broker.py
- requirements.txt
- setup.py
#158 did not actually finish the job of making `Broker.__call__` lazy! As @tacaswell mused aloud in the car this morning, there is a call to `tuple()` in the new `HeaderSource` code that materializes the mongo query before it gets to `Broker.__call__`. This PR finishes the job. It is technically API changes on `HeaderSource`. I advocate tagging (yet another) micro release and pushing this to the floor so that databroker-browser can be responsive.
I also threw in a commit to refactor the dependencies into a requirements.txt and add a missing one. This is a little bit unnecessary but it does no harm.
> API: Make HeaderSource lazy so that Results can be lazy as well.

- databroker/core.py
- databroker/tests/test_broker.py
Assume they are in the 'primary' stream
closes #163
> MNT: support descriptors with out 'name'

- databroker/broker.py
- databroker/core.py
- databroker/tests/test_broker.py
Verified that I got them all with grep:
```
$ git grep header.start
$ git grep header.stop
$ git grep header.descriptors
tests/test_broker.py:    assert [] == header.descriptors
```
and added a test for defense against future changes.
> FIX: Consistently access header fields using __getitem__ not __getattr__.

- databroker/eventsource/shim.py
- databroker/tests/test_broker.py
This allows down-stream to re-reference filled data.
cloes #196 
This still needs tests.
> ENH/API: stash the filled datum id in the filled dict

- databroker/broker.py
> CLN: Remove old _munge_time, which now lives in databroker.eventsource.archiver.

- databroker/core.py
@tacaswell @danielballan @stuartcampbell 
I noticed that the current `register_builtin_handlers` was pulling from `filestore`. This confused me for a while because it was pulling from the old filestore package and not the handlers packaged with `databroker`. 
This fixes that. 
However there still needs to be a call to auto-register the handlers......
> FIX: Fixed location of handlers, was pulling from filestore

- databroker/broker.py
- fill_events in more general
- because documents are no longer dereferenced, `fill_event` either
needs to search for descriptors or the API needs to change for
descriptors to be passed in
- The setup for filling may be non-trivial
> API: deprecate Broker.fill_event

- databroker/assets/utils.py
This makes pymongo actually an optional dependency
> MNT: move pymongo import to be local

- databroker/_core.py
Instead of just using .config in the users folder we now use the correct Windows location
i.e. `%APPDATA%`
I haven't full tested this on Windows yet - having some issues getting all the dependencies working under Windows, namely `ujson` at the moment (I would need to install Visual Studio!).  I think for this release a code review and working for unix is good enough ?
closes #279
> ENH: Support correct location for Windows config

- databroker/_core.py
- databroker/databroker.py
- Do not include `'_legacy_config'` in `list_configs()` output. It is
redundant and (empirically) confuses users.
- Remove duplicate names. Search path precedence will shadow duplicates.
> API: Tweak list_configs()

- databroker/_core.py
- databroker/tests/test_broker.py
The purpose of this line was to alert the user if none of the headers
had a field that the user requested. This of course requires greedily
checking all of the headers, which breaks the laziness of Results.
Based on benchmarking by @ordirules, it can take > 5 minutes to get
the first result out of month's worth of data. Removing this line
reduces that time to < 1 second.
> PERF: Do not call check_fields_exist inside get_documents.

- databroker/headersource/shim.py
This changes the HeaderSource behavior to match the default in the
Header constructor.
This needs tests + discussion
atn @ordirules
> API: return {} instead of None if missing stop document

- databroker/tests/conftest.py
suggested. 
This came from 
```
git diff 8940dc1fc3f16dd76611e389338282739a1ef8e4 1bfed85adfec9b7f89db2adf4ec600dd328371b9
-    from bluesky.tests.conftest import fresh_RE as RE
+    from bluesky.tests.conftest import RE as RE
```
> STY: changed syntax

- databroker/_core.py
- databroker/databroker.py
- databroker/headersource/mongoquery.py
- databroker/tests/test_broker.py
`__getitem__` was too flexible and would return methods as well
as the {'start', 'stop', 'descriptors'} as required to shim dictionary
behavior.
closes #307
> MNT/API: remove unintended API for accessing methods

- doc/source/configuration.rst
- doc/source/creating.rst
- doc/source/index.rst
I think we need this somewhere (discussion about version sentinels). This is a suggestion, feel free to overtake it. 
When I build by the way, I get a few unrelated warnings:
(for ex: doc/source/_as_gen/databroker.Header.values.rst: WARNING: document isn't included in any toctre)
@danielballan
> Doc Add version sentinels

- databroker/_core.py
- databroker/tests/test_config.py
This makes 'temp' a special name so that
```python
Broker.named('temp')
```
is equivalent to
```python
Broker.from_config(temp_config())
```
It provides a nice escape hatch for entry points that only accept
names, not config dicts, such as this one:
```python
configure_base(get_ipython().user_ns, 'temp')
```
> ENH: Support Broker.named('temp')

- databroker/pims_readers.py
@yugangzhang's code still uses `get_images` in some places. We're working to move away from that. However, in the meantime, could we fix the deprecated function? `handler_override` is no loonger an acccepted kwarg thanks!
> BUG: removed invalid kwarg to get_images

- databroker/assets/base_registry.py
- Let the ground truth be in handler_base
- use the exception class stashed on the BaseRegistryRO object to
allow customization by sub-classes and so a registry instance
bring's its exception classes with it
closes #334
> FIX: ensure there is only 1 version of DuplicateHandler

- databroker/_core.py
- databroker/assets/handlers.py
- databroker/assets/handlers_base.py
- databroker/assets/tests/test_handlers.py
Reverts NSLS-II/databroker#308
This breaks sub-classes which passing in 'key' as a string (as is still documented).
> Revert "Refactor HDF5 handlers and add DASK handler"

- doc/source/configuration.rst
- code-block needs a blank line before the code begins or it does
not render as code
- I added some new section headings to make it easier to quickly find things.
- I moved a paragraph that had gotten pushed too far down the page.
- I added some explanation around handlers, with a link to the new assets
section.
> DOC: Fix formatting; add section titles; add more description.

- databroker/_core.py
- databroker/tests/test_config.py
before i forget, i think this may be useful.
@danielballan and I discussed this.
If we want to pass minimal information about the databroker connection between processes, this could be useful. Still need to discuss serialization of headers with @tacaswell 
PS : this is not very clean. If we were to add more features to the config file, we need to remember to modify `get_config` and the test. If anyone has suggestions id like to hear
> Add get_config

- databroker/_core.py
- databroker/eventsource/archiver.py
- databroker/headersource/base.py
- databroker/headersource/client.py
- databroker/headersource/core.py
- databroker/headersource/mongo.py
- databroker/headersource/mongo_core.py
- databroker/tests/test_broker.py
- databroker/utils.py
- doc/source/tutorial.rst
- doc/source/whats_new.rst
- doc/source/whats_new/v0.10.0.txt
These names of confusing, especially 'end_time' because people think
it filters on the time that a run ends. The names 'since' and 'until'
come from `git log`.
Closes #320
I also found some code that should have been deleted in the
"octomerge".
> Rename start_time, end_time -> since, until.

- .travis.yml
This is to try and fix the issue where some of the tests fail once the travis local time goes into 'tomorrow'.
> Added updating Timezone to US Eastern

- databroker/_core.py
- databroker/assets/base_registry.py
- databroker/assets/column_hdf5.py
- databroker/assets/core.py
- databroker/assets/file_writers.py
- databroker/assets/tests/test_fs.py
- databroker/assets/tests/test_fs_mutate.py
- databroker/assets/tests/utils.py
Implements databroker's pieces of
https://github.com/NSLS-II/databroker/pull/322, where Resource and
Datum docs are inserted the same as everything else.
This is designed to work with old ophyd configurations (where ophyd inserts
Resource/Datum docs directly into a Registry) running new ophyd objects (where
the RunEngine collects Resource/Datum docs and emits them). In this case, the
databroker will see two documents with the same uid, which would normally cause
it to error. To ease the transition, we the databroker will emit a warning if
it sees a duplicate insert but then just ignore it. This behavior is
configurable by a new kwarg, which is strict by default in the low-level API.
It is tolerant by default in the high-level ``Broker.insert`` API, only
temporarily to ease this …
> ENH: Implement Broker.insert for 'datum' and 'resource'

- databroker/_core.py
- databroker/eventsource/shim.py
- databroker/tests/test_broker.py
This looks like it's missing (currently trying to read fields only for a certain stream).
tested locally at QAS, still needs test.
> Add stream_name option to fields

- databroker/_core.py
Previously observed by @tacaswell and @jrmlhermitte at ISS, found today at TES.
> CLN: remove print namespace in _core

- databroker/_core.py
Specify was spelled as specifiy.
> ENH: Fixed typo.

- databroker/assets/core.py
Fixed typo: 'datum_col' was spelled 'datam_col' .
> FIX: Fixed typo.

- setup.py
Should fix the default rst rendering at https://pypi.org/project/databroker/:
Attn @danielballan
> BLD: correct rendering of the README.md on PyPI

- databroker/_core.py
The 'name' field is not required by the schema, and we cannot assume that it is
present. It happens that the bluesky RunEngine always includes this field now,
but older documents do not have it, and it is still optional from the point of
view of the schema.
> FIX: Do not assume Descriptors have a 'name' field.

- doc/source/creating.rst
This adds the line `import databroker` above the line `databroker.assets.utils.install_sentinels(db_analysis.reg.config, version=1)`
This import is required for these lines to work.
> Adding an `import databroker` required line

- requirements.txt
To address https://github.com/NSLS-II/PyXRF/issues/159#issuecomment-504426739.
This change may be temporary, as dask may be introduced in the later major versions.
> CLN: remove dask dependency

- doc/source/index.rst
Add all projects toctree to the databroker documentation.
Motivated by https://github.com/NSLS-II/docs/issues/73.
Tested locally by building the documentation.
> DOC: added all projects toctree to databroker

- databroker/assets/mongo_core.py
- databroker/headersource/mongo_core.py
- requirements-test.txt
- setup.py
* `ujson` appears to be a dependency of a dependency, which was not picked up when I installed the requirements in a pre-existing environment
* Deprecation information: https://api.mongodb.com/python/current/api/pymongo/collection.html?highlight=unordered%20bulk#pymongo.collection.Collection.initialize_unordered_bulk_op
* Replaced with: https://api.mongodb.com/python/current/api/pymongo/collection.html?highlight=unordered%20bulk#pymongo.collection.Collection.bulk_write
* bulk_write requires pymongo >= 3.0
> REF: replace deprecated unordered bulk op

- MANIFEST.in
The required files are missing from the source distribution on PyPI. See https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=442 for the details.
> BLD: add missing files to PyPI sdist

- databroker/_drivers/jsonl.py
- databroker/_drivers/mongo_embedded.py
- databroker/_drivers/mongo_normalized.py
- databroker/_drivers/msgpack.py
- databroker/in_memory.py
Currently ``root_map`` can only be set after `__init__`, via
```
cat = SomeCatalogClass(...)
cat.filler.root_map = {...}
```
and, moreover, it does not propagate into serach results. It obviously
should propagate into search results.
And it should be settable via `__init__` for consitency with
``handler_registry`` and so that it can be set in configuration files.
> Add root_map

- databroker/core.py
- doc/source/assets.rst
This is a subtle bug, made difficult by the deep class hierarchy
of intake Catalogs---something we might revisit in intake someday.
The RemoteBlueskyRun was fetching the full, un-paginated /v1/info of its
*parent* catalog (e.g. BlueskyMongoCatalog). This was "harmless" in the
sense that everything still worked, but it was very slow because the
parent catalog can be large.
This is partly of a relic of the early days of intake-bluesky dev when
my mental model of intake was not so good.
> Fix fetch info of BlueskyRun not its parent catalog.

- databroker/_drivers/mongo_embedded.py
- databroker/_drivers/mongo_normalized.py
- databroker/core.py
- databroker/in_memory.py
- databroker/v1.py
Continuing our theme of using entrypoints for discovery, this adds a new
``'databroker.handlers'`` entrypoint which packages can use to declare that
they ship some classes that may be used as handlers for certain specs.
This means that a handler registry can be specified:
1. directly, by passing a dict into the Catalog's `__init__`
2. via a v0-style configuration file that specifies a dict _to be passed_ into `__init__`
3. via an intake-style `catalog.yml` file with the same effect as (2)
4. implicitly, by discovering all installed handlers via the `'databroker.handlers'` entrypoint
Notice that we avoid any potentially-confusing configuration "merging" here.
Approach (4) is only activated if none of the other approaches are used and
thus ``handler_registry=None`` is passed in to the …
> Discover handlers via 'databroker.handlers' entrypoint.

- databroker/core.py
Before this change assembling the DataArrays into one Dataset
raised an error because multiple DataArrays used the same dimension name
(such as ``dim_0``) to mean different things. Xarray detected that
one DataArrays's ``dim_0`` had a different shape than another
DataArray's ``dim_0`` and thus (correctly!) refused to combine them into
one Dataset, raising an error like:
```
ValueError: arguments without labels along dimension 'dim_0' cannot be aligned because they have different dimension sizes: {1, 2, 3, 4, 5, 38, 7, 14, 18}
```
This PR ensures unique dimension names across the whole Dataset. This
fallback will become less important once we start providing names for
the dimensions through ``device.describe()``, making use of the 'dims'
key that was added to the event model.
> Give dimensions unique names.

- databroker/core.py
- databroker/intake_xarray_core/__init__.py
- databroker/intake_xarray_core/base.py
- databroker/intake_xarray_core/xarray_container.py
- requirements.txt
- setup.py
The motivation is to avoid taking on all the format-specific dependencies
in intake-xarray and just use the server--client piece.
> Use vendored intake-xarray.

- databroker/core.py
- databroker/v1.py
Thus, all *new* consumer code, using the `canonical(...)` method, will be
written to expected EventPages and thus do things in an efficient, vectorized
way.
Note that DatumPages were already handled correctly, so no changes were needed
for Datum.
This change exposed some typos in codepaths that were not previously covered.
> API: canonical(...) always returns EventPage, never Event.

- databroker/_drivers/mongo_embedded.py
- databroker/_drivers/mongo_normalized.py
- databroker/core.py
- databroker/in_memory.py
- databroker/tests/test_v2/generic.py
This is an experimental idea that I would like to _try_ in databroker. If we find that it creates more confusion than it alleviates, we should revert it before the `databroker.v2` interface is declared "stable for general users". If we find that it works well, we should explore moving it upstream to intake if @martindurant is game. (Martin, your comments on what follows are welcome here too!)
To help users who don't have a complete mental model of intake, intake overrides `__getattr__` to blur the line between an Entry and its content. If I call `entry.<something>` when I mean `entry.get().<something>` intake will "do the right thing." Thus, I can get along not really understanding the entry/content distinction and sometimes I'm OK. But other times I can't help but bump into it. For …
> Get entry on getitem

- databroker/tests/test_broker.py
- databroker/v1.py
- requirements.txt
The ``Filler.handler_registry`` is not mutable in event-model 1.12.0.
Our nightly Travis builds have been failing ever since event-model 1.12.0 was
released.
> Compat with event-model 1.12.0

- databroker/_core.py
- databroker/_drivers/mongo_normalized.py
- databroker/tests/test_broker.py
- databroker/tests/utils.py
This is apparently a long standing bug!  The old rule would match the prefix anywhere, the new rule matches it only at the beginning.
> Fix uid regex

- databroker/discovery.py
Found a very small typo in discovery.py. 
I investigated adding a pytest to stress this code, but not sure how to setup entry points in a test.
> Fix typo in EntrypointsCatalog

- databroker/core.py
This pattern was stripped out at some point between 1.0.0b3 and current
`master`, and it should not have been. It handles the possibility that one
Event could have multiple datum_ids in it, and thus may need to take more than
one trip through the `try...except UnresolvableForeignKeyError` dance to pull
all the relevant Datum documents.
We should also add a test, but I'm inclined to merge this as a hot fix and open
a separate issue for protecting it with a test. Verified interactively at CHX:
Before:
```py
import databroker
catalog = databroker.catalog.chx
run = catalog['d6013efc']
run
run.primary.to_dask()  # raises UnresolvableForeignKeyError
run.primary.to_dask()  # works
```
After:
```py
import databroker
catalog = databroker.catalog.chx
run = catalog['d6013efc']
run …
```
> Reinstate reentrant fill pattern.

- databroker/tests/conftest.py
- requirements-test.txt
Fixes failures like this one:
<details>
```
______________________________ test_glue[sqlite] _______________________________
db = <databroker._core.Broker object at 0x7f337c3372e8>
RE = <bluesky.run_engine.RunEngine object at 0x7f337c1ba080>
def test_glue(db, RE):
>       from databroker.glue import read_header
databroker/tests/test_glue.py:6:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
databroker/glue.py:3: in <module>
from glue.core.data import Data
../../../virtualenv/python3.7.1/lib/python3.7/site-packages/glue/core/__init__.py:3: in <module>
from .command import Command, CommandStack  # noqa
../../../virtualenv/python3.7.1/lib/python3.7/site-packages/glue/core/command.py:8: in <module>
from glue.core.data_factories import load_data …
```
> Put lower bound on numpy in tests.

- databroker/core.py
Trying to stack a list of scalars can cause dask to fail on old
versions of dask (this was fixed in dask 2.0).
> FIX: support dask < 2

- databroker/_drivers/mongo_normalized.py
- databroker/tests/test_v2/test_mongo_normalized.py
One option of interest is `no_cursor_timeout`. I believe the cursor timeouts
were encountered at XPD or PDF (by @tacaswell? or @mrakitin?). I just
encountered them while trying to do a long export task at FXI.
I think we ought to leave timeouts on by default---they are there for a reason---
but we clearly need the ability to request a timeout-free cursor for the
server for some cases.
This should be documented and tested before being merged.
> WIP: Allow user to pass options to pymongo find.

- databroker/_drivers/mongo_embedded.py
- databroker/core.py
- databroker/tests/test_v2/transform.py
transform functions were getting called twice. the `deepcopies` were added because we discovered that the transforms were modifying documents cached by the drivers.
> transforms bug fix

- databroker/core.py
- databroker/tests/test_v2/transform.py
This was a joint effort from: @tacaswell, @danielballan, and myself. 
Loading runs (BlueskyRun._load()) from a catalog (RSOXS) was taking 200-400ms per run. This was due to the `dask.tokenize` call in intake: https://github.com/intake/intake/blob/master/intake/utils.py#L86
With these changes `BlueskyRuns` are loading in about 20ms
We got rid of some `deepcopy` calls in load, and decided that transforms will be responsible for not mutating the passed in document.
We converted all of the dictionaries in `BlueskyRun` to `OrderedDicts`, so `tokenize` doesn't sort them. `tokenize` spent the majority of its execution time sorting these dictionaries.
Also we register a tokenize method for all Bluesky docs so that they can quickly be tokenized.
We plan to make a PR into intake that helps speed up …
> BlueskyRun._load() optimization

- databroker/_drivers/mongo_embedded.py
- databroker/_drivers/mongo_normalized.py
- databroker/core.py
- requirements.txt
~This is stale work (from November) which may be the complete wrong approach. I am opening this PR to make the work more easily visible.~
This has evolved and now seems like the correct approach. Example with DEBUG logging turned up:
When a file-based ("in-memory") catalog is instantiated, it creates all of its entries greedily. We see that logged here.
```py
In [1]: catalog = BlueskyMsgpackCatalog(f'{directory}/*.msgpack')                                                                                
Created Entry named '35fb6cca-846b-4bbf-9f68-8b01f9c75503'
Created Entry named '7711ad85-43d1-4777-b1f9-e7d581a1057c'
```
When we access a given run for the first time, BlueskyRun (or a sublcass of it, in this case) is instantiated and, as part of that, the data is loaded.
```py
In [2]: …
```
> Cache Entries and DataSources better.

- databroker/tests/test_v2/test_dask_filler.py
Just some cleanup so that the tests run without issuing warnings. This will make it easier to notice any _important_ warnings that show up later.
> Address warnings from Filler.

- doc/source/v1/archiver.rst
During the use of the example for the archiver appliance at ISS, noticed the example is wrong (should be `hdr.table(...)` rather than `db.table(...)`).
Also, <kbd>G</kbd>+<kbd>Q</kbd>'d the blocks of text.
> DOC: correct the archiver doc

- databroker/v2.py
This ensures that we can do
```py
broker_instance.root_map.update(...)
```
whether the `root_map` to initalized as empty or nonempty.
> Make root_map always a dict.

- databroker/core.py
- databroker/tests/test_v2/generic.py
I think the metadata should be initialized at init time. Is there
any harm in calling `_load` there?
> Include 'descriptors' in stream metadata.

- databroker/core.py
- databroker/tests/test_document.py
The tests that _all_ dict methods that would mutate the documents, including lesser-used ones like `popitem`, raise `NotMutable` as they should.
It also allows `copy.deepcopy(Document(...))` to work, whereas on the `master` branch it is necessary to do `copy.deepcopy(dict(Document(...))`.
@tacaswell At some point early on in defining `Document` I floated the idea of a more aggressive override of `__deepcopy__` and you talked me out of it. I forget exactly what I was proposing then, but I think what I've done here is fairly gentle and beneficial. Agree?
This also prompts the question, "What should `Document(...).copy()` do? "Currently we do not override it, so it falls back to `dict.copy()` returns a plain `dict` with a shallow copy of the original `Document`. Recall that we also support …
> Document mutability cleanup

- databroker/eventsource/archiver.py
This is a fix for the returned data from the archiver (`_table_given_times(...)` method), which was originally in the UTC timezone. The problem was observed with the ISS archiver appliance, see https://github.com/elistavitski/profile_sample-environment/blob/master/startup/00-startup.py.
Here are the examples of returns before and after the fix.
Before:
=====
```py
In [1]: import databroker
In [2]: databroker.__version__
Out[2]: '0.13.0'
In [3]: import datetime
In [4]: datetime.datetime.now().isoformat()
Out[4]: '2020-01-28T11:59:09.239276'
In [5]: d = arch_iss.tables_given_times(ttime.time()-1*24*3600, ttime.time())
In [6]: d['rga_ch1'].head()
Out[6]:
time          data
0 2020-01-27 16:59:02.682578613  5.822290e-10
1 2020-01-27 17:00:19.692776855  5.677490e-10
2 2020-01-27 …
```
> Fix the timezone for the archiver-returned data

- databroker/core.py
- databroker/tests/test_v2/generic.py
* Use `_repr_pretty_` for any multi-line reprs.
* Consistently use the actual (sub)class name
(`self.__class__.__name__`) in `__repr__` but use `BlueskyRun` in all
`_repr_pretty_` to hide the remote vs. local distinction and the
distinction between `BlueskyRun` and `BlueskyRunFromGenerator`, which
is not intended to be an end-user-facing distinction.
Closes #532
> Clean up __repr__s.

- databroker/_drivers/jsonl.py
- databroker/core.py
- databroker/tests/test_v2/test_core.py
- databroker/tests/test_v2/test_jsonl.py
- doc/source/v2/developer/reference.rst
There are many utility methods in `core` that were written in prep for a
refactor of `databroker_to_xarray`, some of which are not actually used yet,
and maybe all of which could be moved to `event-model` because they are
generically useful for manipulating Documents. In prepartion for possibly
moving and/or re-tooling them, I have made them private except for those
that are imported to drivers.
I also moved `tail`, which a text-parsing utility only used by the JSONL driver,
into the JSONL driver.
> Reduce public API before release.

- .flake8
- .travis.yml
- databroker/__init__.py
- databroker/_drivers/mongo_embedded.py
- databroker/_drivers/mongo_normalized.py
- databroker/core.py
- databroker/discovery.py
- databroker/in_memory.py
- databroker/queries.py
- databroker/tests/conftest.py
- databroker/v1.py
- examples/generate_mongo_data.py
- examples/generate_mongo_embedded_data.py
- examples/generate_msgpack_data.py
Inspired by https://github.com/bluesky/ophyd/pull/823 and https://github.com/bluesky/bluesky/pull/1326, this runs `flake8` in the databroker CI and brings (some of) the codebase into compliance.
The flake8 configuration file excludes modules, scripts, and tests related to v0 because the v0 code is expected to be deprecated and removed once v1 (which provides a v0-compatible API shimmed on top of v2) in proven reliable.
Changes include whitespace, removing unused imports, reordering imports, removing some unused local variables, adding some missing f-strings, and fixing some misspelled variables on a new codepath that is apparently untested.
> Flake8 compliance

- setup.py
Code was not actually valid Python 2 syntax, so the nice error never
showed. Testd with `python2 setup.py sdist`.
> Fix python2 codepath.

- databroker/core.py
If we don't have a stop document, the `run.metadata['stop'] is None` which seems reasonable, we don't have a value for it yet and it is up to the consumer to do something sensible in this case.
However, when we call `run.cannonical()` we expect valid `(name, doc)` pairs.  Previously we were yielding out the `None` which was causing downstream tools to choke.
A better solution may be to keep a running count of the event/event_page documents and fabricate a missing stop document.  That does require a bit more thought as to what the exit status should be.
> FIX: if no stop document don't emit None

- databroker/core.py
- databroker/tests/test_glue.py
- databroker/v1.py
- doc/source/v1/tutorial.rst
This PR adjust for changes in intake that will be introduced in
intake/intake#490. This branch has been tested against that PR branch, as well
as intake `master` and the most recent intake release, `0.5.5`.
This is how it looks interactively against that PR branch:
```py
In [1]: import databroker                                                                                                                                                                     
In [3]: list(databroker.catalog)                                                                                                                                                              
Out[3]: 
['dev1',
'dev2',
'fxi_feb',
'test1',
'test_unpack1',
'test_unpack3',
'dev',
'csx',
'example']
In [4]: databroker.catalog.dev1 …
```
> Adjust for Entry unification

- databroker/tests/test_v2/generic.py
The bug in question was fixed in the course of finishing #569. This just adds
a test to ensure it does not creep back in.
> Test for AttributeError vs RecursionError.

- databroker/core.py
- databroker/tests/test_v2/test_multi_descriptor.py
This demonstrates a failure when multiple descriptors of the same name are present. 
One test succeeds, while the other fails with:
```
databroker\tests\test_v2\test_multi_descriptor.py:65 (test_multi_descriptors_same[multi_descriptor_doc_stream0])
multi_descriptor_doc_stream = <generator object multi_descriptor_doc_stream.<locals>.doc_gen at 0x00000254199AF048>
@pytest.mark.parametrize("multi_descriptor_doc_stream", (["primary", "primary"],), indirect=True)
def test_multi_descriptors_same(multi_descriptor_doc_stream):
>       _test_ingest_to_xarray(multi_descriptor_doc_stream)
test_multi_descriptor.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_multi_descriptor.py:58: in _test_ingest_to_xarray
assert …
```
> Add test for extracting xarrays from document streams with multiple descriptors with same/unique names. 

- databroker/_drivers/jsonl.py
- databroker/core.py
- databroker/in_memory.py
- databroker/tests/test_v2/generic.py
- databroker/tests/test_v2/test_jsonl.py
- databroker/tests/test_v2/test_mongo_embedded.py
- databroker/tests/test_v2/test_mongo_normalized.py
- databroker/tests/test_v2/test_msgpack.py
* If a __getitem__ lookup fails, try again after forcing a reload.
* Proactively force a reload before recency-based indexing (e.g.
``catalog[-1]``) because a stale cache is a big problem in that case.
This is dashed off and needs careful thought before merging. ~Also, it should be applied to the mongo drivers if indeed it is to be merged.~
> Try __getitem__ again with a forced reload.

- databroker/tests/test_v2/test_mongo_normalized.py
- doc/source/v1/api.rst
The new `stats()` method introduced in #584 was (automatically) documented in
the v2 reference documentation, but because of the way v1 documentation is
organized it had to be manually added there.
Also, while I was here I added a unit test for `stats()`.
> Add test for 'stats' method and further document it.

- databroker/projector.py
- databroker/tests/test_projector.py
Implementation of projector that can be called with a BlueskyRun, reading a projection as specified in https://github.com/bluesky/event-model/pull/179
This is the result of lots of discussion with @ronpandolfi  and @tacaswell. 
The result is an xarray.Dataset. Single value fields (like those that might appear in the start doc) would be projected into the Dataset's attrs field. Multi-value event stream fields appear in the Dataset with the projection's key and a Datarray value.
The projection can also support calculable fields. The projection type "calculation" can specify a callable that can be invoked by the projector to populate a Datarray into the return Dataset.
There was also a suggestion for a static type in projections where a value was pulled directly out of the projection. I'm …
> Projector implementation

- databroker/core.py
This failed in the env var was unset because it tried to convert `None`
to an `int`.
> Fix env var parsing.

- databroker/_core.py
- databroker/assets/core.py
- databroker/core.py
Debugging problems resulting in DatumNotFound exceptions is made easier if the corresponding event can be quickly found.
This PR adds EventDatumNotFound to carry the event uid and corresponding datum id.
> add EventDatumNotFound exception

- databroker/core.py
- databroker/discovery.py
- databroker/tests/utils.py
- databroker/v2.py
- doc/source/v2/user/index.rst
- requirements-test.txt
This is the location of `RemoteCatalog` on the default branch of intake, I suspect it is better to shim it here and make sure the deprecation is noted in intake.
> MNT: Adjust to changes in intake

- databroker/core.py
- databroker/tests/test_v2/generic.py
- databroker/tests/test_v2/test_core.py
- requirements.txt
Recall that devices implement `read()` and `read_configuration()`. Respectively, these produce readings that go into Events and configurational readings that go into Event Descriptors. Each of these readings include both values and associated hardware timestamps.
```py
In [1]: from ophyd import Device, Component
In [2]: from ophyd.sim import Signal, SynSignal
In [3]: import random
In [4]: class Thing(Device):
...:     intensity = Component(SynSignal, func=random.random)
...:     exposure_time = Component(Signal, value=1, kind='config')
...: 
In [5]: thing = Thing(name='thing')
In [6]: thing.read()  # These will go into the Event.
Out[6]: 
OrderedDict([('thing_intensity',
{'value': 0.008608399314166015, 'timestamp': 1603384540.002283})])
In [7]: thing.read_configuration()  # These will go …
```
> Expose timestamps, configuration, and configuration timestamps in v2.

- databroker/core.py
- requirements.txt
We use `extract_shape` to work around the fact that many old documents have
wrong shape metadata. Until we go back and fix old documents, this is how we can
make them readable by "v2", which unlike "v1" relies on `shape` actually being
accurate.
Needs a new event-model release and an increased minimum version pin.
> More shape extraction heuristics.

- databroker/core.py
- databroker/tests/test_v2/generic.py
- databroker/v1.py
- doc/source/v2/developer/index.rst
- doc/source/v2/user/index.rst
The old method is still supported and issues a warning.
Closes #618. See that issue for context and motivation.
> Rename 'canonical' to 'documents'.

- databroker/projector.py
- databroker/tests/test_projector.py
This PR primarily creates a simplified projector. Before this, the only projector available was the project_xarray function which is comprehensive and builds up an xarray.Dataset with data from the full run.
That is pretty heavy weight, and potentially overkill for applications when want two things:
- a quick summary of a few metadata fields when presenting a list of runs
- projected fields
So, this uses the same rules for selecting a projection that the xarray projector uses, but only projects metadata from the start document. It also has a parameter that allows callers to send a list of just a few fields that they want. I had support of GraphQL in mind there.
Maybe we want to add stop document info too? A summary might want to know whether runs completed and how many events they have.
> Summary projector

- databroker/core.py
- databroker/tests/test_v2/generic.py
In #623 we renamed `canonical` to `documents` and made a back-compatible shim for `canonical`. I gave it the wrong signature and also called it with that (wrong) signature in the tests. Fixed to have the proper signature.
> Fix back-compat shim.

- databroker/__init__.py
- databroker/assets/sqlite.py
- databroker/discovery.py
- databroker/headersource/sqlite.py
With the latest release of intake 0.6.1 we see this problem:
It should behave like this:
This PR fixes the problem.
> MergedCatalog is no longer working due to intake change

- databroker/__init__.py
- databroker/discovery.py
Import MergedCatalog from a better location so that it still works with older intake versions
> fix import error for older intake version

- .github/workflows/testing.yml
- requirements-test.txt
- requirements.txt
We are seeing CI failures due to the latest intake release 0.6.2, and also from dask 2021.3.0.
Intake no longer supports python 3.6. 
This PR drops support for python 3.6, in accordance with https://numpy.org/neps/nep-0029-deprecation_policy.html
I turned off the CI for python 3.6, and turned on the CI for 3.9
> Drop python 3.6 support, and skip dask 2021.3.0

- databroker/v1.py
This corrects a typo in the format string for mongodb uris, and also adds an optional authsource configuration to the connection string.
@dylanmcreynolds @JulReinhardt @ihumphrey
> Fix format string; add authsource option

- databroker/intake_xarray_core/xarray_container.py
- requirements.txt
In this PR, we try fixing the dask 2021.3.0 issue in a better way than skipping this dask version
> Dask 2021.3.0 issue

- .github/workflows/testing.yml
- databroker/queries.py
- databroker/tests/conftest.py
- databroker/tests/test_v2/test_jsonl.py
- databroker/tests/test_v2/test_mongo_embedded.py
- databroker/tests/test_v2/test_mongo_normalized.py
- databroker/tests/test_v2/test_msgpack.py
- databroker/tests/utils.py
- databroker/v1.py
- requirements.txt
Implement 4 versions of the required compatibility shim.
Tests do not pass with tzlocal v3 without these changes, locally tested they still work with v2.
If we want to skip #671 we can squash this and close that PR.
> Fix tzlocal support

- requirements.txt
Due to incompatible changes in v3, pin to older versions.
> BLD: pin tzlocal back

- databroker/v1.py
This PR fixes an issue with accessing `run.metadata` in the stop document.
A small update to access metadata properly.
Internal NSLS-II JIRA report for the CSX beamline.
Nothing yet.
> FIX: fix metadata access from a run via attribute

- databroker/assets/core.py
- databroker/assets/sqlite.py
- databroker/headersource/core.py
- databroker/headersource/hdf5.py
- databroker/headersource/sqlite.py
- requirements-test.txt
- requirements.txt
Intake 0.6.5 seems to have a bug in it causing errors in databroker.
So the CI run against intake master is expected to fail.
See issue https://github.com/intake/intake/issues/643
Pymongo 4 dropped `Collection.insert()` so we have to use `Collection.insert_one()` or `Collection.insert_many()`
> don't use intake v0.6.5, and get the CI passing

- .github/workflows/testing.yml
- continuous_integration/scripts/install.sh
- databroker/replay/replay.py
- requirements-server.txt
Adds a script that replays Bluesky runs with the correct timing.
This simulates live streaming data so we can develop and test code for streaming data without needing to be at a beamline looking at new data.
This has been tested interactively while developing GUI applications.
> Add replay script

- databroker/__init__.py
The back-compat shim needs to fallback to the nested databroker sub-module not utils.
> FIX: the back-compat getattr shim in databroker

- databroker/experimental/server_ext.py
- databroker/tests/test_experimental.py
This fixes a bug where `specs` were accepted and saved but not exposed back to the client when the data was accessed. (The list of `specs` was always empty.)
> Expose 'specs'.

- databroker/experimental/schemas.py
- databroker/experimental/server_ext.py
- databroker/tests/test_experimental.py
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
This PR changes only the alpha experimental backend.
This PR switches from HDF5 for Zarr for array storage because the latter has first-class support for concurrent writes of non-overlapping chunks. For DataFrame storage, it continues to rely on parquet, but it switches from a single parquet file to a directory of parquet file(s), supporting partitioned data.
It also adds support for Tiled's new `sparse` structure family, backed also be a directory of parquet files.
> [Experimental backend] Support chunked upload and sparse arrays

- databroker/experimental/server_ext.py
- databroker/tests/test_experimental.py
Slicing into an DataFrameClient should return an ArrayClient. This was not implemented in the experimental server, and failed like so:
```py
In [3]: c
Out[3]: <Node {'5804f003-6faf-43f2-8406-01533619f032', ...} ~3 entries>
In [4]: import pandas
In [5]: df = pandas.DataFrame({"a": [1,2,3], "b": [4,5,6]})
In [6]: x = c.write_dataframe(df)
Out[6]: <DataFrameClient ['a', 'b']>
In [8]: x
Out[8]: <DataFrameClient ['a', 'b']>
In [9]: x.read()
Out[9]: 
a  b
0  1  4
1  2  5
2  3  6
In [10]: list(x)
Out[10]: ['a', 'b']
In [11]: x['a']
---------------------------------------------------------------------------
HTTPStatusError                           Traceback (most recent call last)
~/Repos/bnl/tiled/tiled/client/utils.py in handle_error(response)
24     try:
---> 25 …
```
> Fix slicing into WritableDataFrameAdapter.

- databroker/cli.py
- databroker/shape_fixer.py
- requirements-server.txt
- setup.py
This adds a CLI to databroker. In this PR it only has one command, but it is expected to grow more.
This captures [the "shape-fixer"](https://github.com/danielballan/migration/blob/main/shape_fixer.py) which we use to retroactively edit the `shape` in the EventDescriptor to match the actual shape. This is intended to make it easily usable by people other than me. :-)
The shape-fixer has been used on about ten beamlines. This exact PR branch was run at ISS today.
> Add CLI with shape-fixer.

- databroker/experimental/schemas.py
- databroker/experimental/server_ext.py
- databroker/server.py
- databroker/tests/test_experimental.py
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
This PR implements a new approach in the use of references as an additional field in the document. It's use is similar to what we are doing with specs as a list of strings but references will consist in a list of `ReferenceDocument` object that can store a label and a url. The `references` object does not sit inside `metadata`; it seems more appropriate to leave it at the same level of `metadata` and `specs`
> Added and implemented new references schema

- databroker/mongo_normalized.py
* caching was keeping hold of documents that are never cleared within normal usage within the production system, resulting in overrunning memory and crashed tiled instances
Remove @lru_cache decorators from functions in DatasetFromDocuments() that led to tiled crashes.
#740 
Tested locally with the same server environment described in the issue. After changes, memory usage never went above 1.0% with the same dataset that was causing the server process to increase at 10GB per client run.
> remove caching

- databroker/client.py
Breakage was in https://github.com/bluesky/tiled/commit/eb4700bbf3c30bfcde4088bf499c3901524099ad, first released in v0.1.0a76. Detected by CHX beamline staff.
> Adjust for API change in tiled.

- Dockerfile
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
This is not expected to affect the library itself at all. But the `CMD` on the base docker image has changed in `v0.1.0a84`, and we want to propagate that changed into a tagged databroker image.
> Bump tiled minimum versions and base image.

- databroker/common.py
- databroker/mongo_normalized.py
- databroker/tests/test_access_policy.py
The `access_policy` was being dropped on the floor instead of propagated through. This is, obviously, a critical fix. It was not caught because the tests use in-memory MongoDB (`from_mongomock`) not networked MongoDB (`from_uri`). Integration tests at NSLS2 now check this.
> Propagate access policy through constructor.

- Dockerfile
I discovered while deploying at NSLS2 a couple weeks ago that one or more of these (at least `humanize`) is imported by the server. Not sure it _should_ be but for now I'd like to just fix the image in the most direct way possible.
> Include 'back-compat' deps in image.

- databroker/tests/test_config.py
- databroker/v1.py
`Broker.named('temp')` is a convenience for making a Broker backed by an in-memory store. We disabled it when we were drafting v2 (raised `NotImplementedError`) but now we should restore it.
> Restore Broker.named('temp') in v2.

- databroker/mongo_normalized.py
- databroker/tests/test_queries.py
Distinct is applied over the start and stop collection.
This implementation follows the same idea and is compatible with the structure that tiled is using already.
distinct checks for keys in metadata, for structure families and for specs while it remembers previous search queries to apply the analysis over specific child nodes and not the root node.
Example: `c.search(Key("x")=="a").search(Key("y")=="b").distinct("z", structure_families=True, specs=True, counts=True)`
> Added distinct to MongoAdapater class

- Dockerfile
Bump the tiled version. No specific motivation, just keeping the image current.
I also removed the vestigial `docker/` directory. (We now keep the `Dockerfile` in the repo root, and have for some time.)
> Bump tiled version in image.

- databroker/queries.py
If someone does
```py
catalog["uid"]  # "uid" a literal string
```
where they meant
```py
catalog[uid]  # uid a variable
```
the error message is
```
Partial uid uid is too short. It must include at least 5 characters.
```
We want
```
Partial uid 'uid' is too short. It must include at least 5 characters.
```
> Improve error message.

- databroker/client.py
- databroker/mongo_normalized.py
- databroker/tests/test_queries.py
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
Tiled is renaming the structure family `node` to `container`. The term "node" will now be used to refer to _any_ item in Tiled's data model, be it an array, dataframe, container, etc. https://github.com/bluesky/tiled/pull/478
This PR adjusts for that. The tests will not pass until Tiled is next released.
> Adjust for API change in Tiled

- databroker/mongo_normalized.py
- databroker/tests/test_broker.py
This fixes a bug that was reported as an issue with `baseline` readings. The underlying problem was with string columns, which happened to appear in the `baseline` stream in this instance. It was a two-character fix for a bug introduced 3 weeks ago, in #781.
A unit test reproduces the bug in the first commit, and the second commit fixes the bug.
> Test string column

- databroker/assets/mongo.py
- databroker/headersource/mongo.py
When databroker was for both *writing* and reading it made some sense to put this here. Now it should be the job of writers (suitcase) or perhaps some separate separate, ops-oriented code.
If this did no harm it might make sense to leave it in v0, but it raises errors when it clashes with the evolving index creation in other repos, as illustrated in #600.
Closes #600
> Remove index creation.

- databroker/assets/tests/test_mongo_details.py
- databroker/mongo_normalized.py
- databroker/tests/utils.py
- requirements-server.txt
- requirements-test.txt
Update usage of `ArrayAdapter`.
Tiled made backward-compatible changes in https://github.com/bluesky/tiled/pull/537. The databroker adapter was not fully updated to account for this. The issue went un-caught because it only occurs on a codepath where a databroker handler returns a Dask Array. This is not tested.
I tested this interactively by looking at two pieces of real beamline data:
* https://tiled-demo.blueskyproject.io/ui/browse/bmm/raw/5631b9e1-b07d-4455-ae85-36e9a84ab7dc/primary/data/I0
* https://tiled-demo.blueskyproject.io/ui/browse/fxi/raw/1b0b4d73-6d87-43ab-8d62-ed035c51b9b4/primary/data/Andor_image
...using current `main` (broken) and this PR branch (currently deployed, works).
There _should_ be a unit test but that would actually be a pretty big addition to the current …
> Fix compat with tiled API changes.

- databroker/mongo_normalized.py
- databroker/tests/test_validate_shape.py
This PR helps solve an issue seen at the SRX beamline and could be encounter in other beamlines possibly.
Initially, it was noticed that the adapter was failing because the hardware was passing incomplete rows of data with inconsistent shapes.
This PR adds the option to select a validator that evaluate the correct shape of the data being passed to the adpater
> Define validate shape of descriptor

- databroker/client.py
This PR improves on #790  by using `newline` delimiter to check for the completeness of streamed JSON objects instead of catching `JSONDecodeError`.
The `splitline` method called on decoded chunks of streamed JSON sequences is passed the argument `keepends=True`. That way it preserves the `newline` character at the end of each split, if any. Checking for its existence is used as a more robust way of detecting a complete JSON object.
If `JSONDecodeError` is raised for a legitimate reason the previous implementation would mask the exception and go on to do something it is not supposed to do by trying to mash together JSON objects incorrectly. A more robust implementation is to check for the presence of a `newline` delimiter to detect the end of a streamed serialized JSON object.
This change …
> Improve  JSON sequence deserialization using `newline` delimiter instead of `try except`

- databroker/tests/test_broker.py
Following guidance in https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests
> Avoid deprecated usage for pytest 8.

- databroker/mongo_normalized.py
This PR fixes an error identified while trying to read an array inside an xarray.Dataset with a dimension size greater that 2
This error was identified and tracked while trying to read some data from BlueSky runs for the Data Security project at SRX.
It was identified that the` xs_flour` array was returning an error while data was requested through the `,read()` method in its parent node. This means that these two examples were failing:
```
c['srx']['raw'][152589]['stream0']['data'].read()
c['srx']['raw'][152589]['stream0']['data'].read('xs_fluor')
```
Initially, it was thought the problem was on the client side but the error was tracked all the way to the server side and it was identified that the error was being saved with the document at the moment this one was built.
It was also …
> Fixed definition of xarray dimensionality during build configuration

- databroker/mongo_normalized.py
This adds the ability for the raw blueskyRun and BlueskyEventStream objects to update their metadata, putting the onus on clients that invoke it to preserve existing metadata. Currently behaves like a `PUT` request, overwriting the existing data unless the client performs a `copy.deepcopy()` of the extant metadata dict.
Here is the code for performing such an update, keep in mind that the client should now be refactored with friendlier facilities for performing this action including HTTP `PATCH` requests like `rfc6902`. Potentially this would manifest as 
- update_metadata (alias)
- patch_metadata
- put_metadata
```
import tiled
import copy
from tiled.client import from_uri
c = from_uri("http://localhost:8000",api_key="secret")
metadata = copy.deepcopy(dict(c[154705].metadata)) …
```
> Support updating metadata from Tiled client 🧱

- requirements-server.txt
- requirements-test.txt
This supports updates of `stop` and `descriptor` documents.
> Bump minimum version of suitcase-mongo.

- .gitignore
- databroker/mongo_normalized.py
- databroker/tests/utils.py
- requirements-test.txt
Tests are failing in GitHub CI and locally on my laptop.
* [Create indexes for mongo-legacy backend](https://github.com/padraic-shafer/databroker/commit/81d9c6374b63314c9ad604f902c1306348304a59)
* [Pin glue-core to keep glue.qglue](https://github.com/padraic-shafer/databroker/commit/5be59a74906eeb2b8ac7d5bcdde1f25bfae0ce4f)
* [Add .structure() to mongo_normalized adapters](https://github.com/padraic-shafer/databroker/commit/995cc95c20879550a144beae7bbb4439ef5f61af)
* [Keep .env secrets out of project repo](https://github.com/padraic-shafer/databroker/commit/451e4239753568dde0646d1d3a89de303ef2f024) 
Currently tests are failing; these changes enable test suite to pass without loss of functionality.
Tested locally on MacOS (M2) with fresh instances of Mongo:(5, 6, 7) available on port 27017 …
> Update dependencies to make tests pass

- databroker/_core.py
- databroker/client.py
- databroker/tests/test_broker.py
- databroker/utils.py
Databroker will now accept a `numpy.int64` value as a key for accessing scans in a databroker catalog, ~~as long as that value can be safely converted to a python int (int32). Otherwise a `KeyError` is raised.~~ Behavior of using the int-valued key is unchanged by this PR: The key is treated as a `scan_id` value if positive, or the `N`th-most recent scan index if negative. Suitable unit tests have been added to verify this.
Databroker is frequently used in conjunction with pandas. By default pandas imports integer columns as `numpy.int64`; databroker then raises an exception when someone tries to use the int64-valued `scan_id` as a catalog key.
Although type conversion could be done manually by the calling code, this is such a common scenario that it would improve out-of-the-box user …
> Accept numpy.int64 as databroker catalog key

- Dockerfile
The minimum version required is unchanged; this just bumps the version we derived from in `Dockerfile`
> Bump tiled in Dockerfile to v0.1.0b2

- databroker/mongo_normalized.py
- databroker/tests/test_broker.py
We saw a failure on numpy 2.0 due to an untested codepath in the case of nonscalar data placed directly in an Event document.
New unit test exercises the bug:
```
FAILED databroker/tests/test_broker.py::test_direct_img_read[mongo-tiled-False] - AttributeError: module 'numpy' has no attribute 'product'
FAILED databroker/tests/test_broker.py::test_direct_img_read[mongo-tiled-True] - AttributeError: module 'numpy' has no attribute 
'product'
```
> Numpy 2 fix

- requirements-server.txt
This addresses a bug caught in prod, where the databroker container image is missing this dependency. It comes up in situations when a `ScanID` where is mixed with other query types.
> Add mongoquery as a server dep.

- databroker/mongo_normalized.py
Add support for using dtype_numpy as in ophyd-async
ophyd-async uses `dtype_numpy` as an equivalent for the old `dtype_str`
> Add support for using dtype_numpy as in ophyd-async

- Dockerfile
- databroker/server.py
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
Tiled v0.1.0b8 dropped `PatchedStreamResponse` because said patch is not longer needed, due to a change in Starlette. This changes Databroker to use the Starlette object instead.
> Update for tiled v0.1.0b8

- databroker/v1.py
Even though the property is deprecated, we should maintain type stability
> FIX: return and empty dict for type stability

- databroker/mongo_normalized.py
Reduce `TARGET_PAGE_BYTESIZE` to 8_000_000.
10_000_000 target was found to produce pages too close or just above the MongoDB's hard limit of 16MB.
> reduce `TARGET_PAGE_BYTESIZE` to `8_000_000`

- databroker/mongo_normalized.py
- databroker/tests/test_broker.py
Data is typically chunked using a heuristic. We support a `"chunks"` key, next to `"shape"` in the descriptor, as a way to override the heuristic. This has been in the codebase for quite awhile but evidently not ever actually _run_ because it is broken. This fixes it and adds a unit test. The fix was also tested in the wild:
```py
In [1]: from tiled.client import from_profile, show_logs
In [2]: c = from_profile('tes')
In [3]: c['95820398-d829-4088-a023-746a78c01f4f']['primary']['data']['fluor']
```
Looking forward, we agree that StreamResource will enable chunking. Putting chunks in the descriptor is just an escape hatch for legacy documents.
> Fix and test 'chunks' escape hatch.

- databroker/mongo_normalized.py
- databroker/tests/test_validate_shape.py
We had several design discussions about implicit padding and trimming.  I think it probably isn't the right choice to pad and trim by default, because it can affect scientific results.  This PR fixes a bug with the implicit padding and adds tests.
I think more investigation is required to figure out how to pad and trim in a better way, that is out of the scope of this PR. - @gwbischof 
`default_validate_shape` had some trimming logic that wasn't doing anything, the trimming was happening elsewhere in the code.
`default_validate_shape` was falling for multi-dimensional data.
Buggy logic:
```
loop:
compute padding args
apply padding
```
Fix:
```
loop:
compute padding args
apply padding
```
> FIX: data padding bug in mongo_normalized

- databroker/mongo_normalized.py
- databroker/tests/conftest.py
- databroker/tests/test_access_policy.py
- databroker/tests/test_validate_shape.py
- requirements-test.txt
> Chunking and Padding

- .github/workflows/testing.yml
- databroker/headersource/sqlite.py
- databroker/mongo_normalized.py
- databroker/tests/conftest.py
- databroker/tests/test_access_policy.py
- databroker/tests/test_config.py
- databroker/tests/test_validate_shape.py
- requirements-client.txt
- requirements-server.txt
- requirements-test.txt
- Bumped minimum Tiled version to latest
- Tiled AccesControlPolicy methods grew an additional required parameter, `path_parts`, and changed from sync to async.
- Tiled auth-related parameters changed.
- Python 3.8 is EOL. Python 3.12 was added. Python 3.13 was not yet added, as Tiled is not testing against it 3.13. (Last we checked some of our dependencies were still catching up.)
> Address bit rot

- requirements-client.txt
This can now be added because `bluesky-tiled-plugins` is released on PyPI.
On CI, it works as before: we install from source.
> Add bluesky-tiled-plugins dep

- databroker/mongo_normalized.py
Python deprecated `datetime.utcnow()` and the recommended replacement returns a localized timestamp. This change is necessary for compat with a corresponding change in Tiled.
> Refactor deprecated utcnow method.

- requirements-server.txt
This PR adds `bluesky-tiled-plugins` as a "server" dependency.
The sub package `bluesky-tiled-plugins` is used by the databroker server that gets built as a docker image. Starting up the container fails with the message:
```
│ /opt/venv/lib/python3.12/site-packages/databroker/query_impl.py:16 in        │
│ <module>                                                                     │
│                                                                              │
│    13 │   QueryValueError,                                                   │
│    14 │   Regex,                                                             │
│    15 )                                                                      │
│ ❱  16 from bluesky_tiled_plugins.queries import (                            │
│    17 …
```
> Add bluesky-tiled-plugins as a server dependency

- databroker/mongo_normalized.py
The `case_insensitive` attribute was removed from `FullText` a little more than a year ago in https://github.com/bluesky/tiled/commit/eb79bdb8aea1dec2601c29344e22deedc9f87799#diff-39c6c64d38798eb3df5586ef8342fc2f7b947a43b8f762368f0ef4d2e8545a8d. This needs to be updated to match.
> Adjust to API change in FullText query.

- databroker/mongo_normalized.py
Tested against production database at NSLS-II. On `main`, using the API key of an unrecognized Service Principal produces a 500 error:
```
ValueError: Principcal Principal(id=131, time_created=datetime.datetime(2024, 5, 23, 14, 12, 38, 248410, tzinfo=datetime.timezone.utc), uuid=UUID(uuid=56001d0c-cb9d-4415-8b16-84ded6881b09'), type=<PrincipalType.service: 'service'>, time_updated=None, identities=[], roles=[Role(name='user', description='Default Role for users.', time_created=datetime.datetime(2022, 2, 9, 16, 7, 54, 870299, tzinfo=datetime.timezone.utc), id=1, scopes=['read:metadata', 'read:data', 'apikeys', 'write:metadata', 'write:data', 'create'], time_updated=datetime.datetime(2022, 12, 9, 12, 38, 50, 883734, tzinfo=datetime.timezone.utc))]) has no identity from provider pam. Its …
```
> Handle service principles in access policy.

- databroker/assets/tests/test_handlers.py
- databroker/mongo_normalized.py
- databroker/tests/test_broker.py
An event document containing a `datum_id` still has the associated timestamp inline. Don't try to fill it.
Unit test reproduces a bug found on the floor and fails, next commit fixes the failure.
> Fix access to timestamps in external data_keys

- databroker/mongo_normalized.py
Apply custom transformations to Datum documents.
This enables modifications to Datum documents with custom beamline-specific transforms defined in tiled-site-config.
This is needed as part of the migration from Mongo to SQL storage backend.
Tested with beamline data from HXN as part of the migration.
> Allow modification of Datum documents

- bluesky-tiled-plugins/bluesky_tiled_plugins/bluesky_run.py
- bluesky-tiled-plugins/bluesky_tiled_plugins/catalog_of_bluesky_runs.py
- bluesky-tiled-plugins/bluesky_tiled_plugins/document.py
- databroker/tests/test_broker.py
A follow-up PR to #841. Trying to access v3 clients from v2 Mongo-based catalogs raises a `NotImplementedError`.
Added a test in `test_broker.py`
> Raise a v3 NotImplementedError

- databroker/mongo_normalized.py
- databroker/tests/test_broker.py
See below. 
The `replace_metadata` signature was updated for `BlueskyRun`, but not for `BlueskyEventStream`. See [recent release](https://github.com/bluesky/databroker/compare/v2.0.0b60...v2.0.0b61) and 7f4c901.
Was found when trying to update chunking for RSOXS. 
```
File "/opt/venv/lib/python3.12/site-packages/tiled/server/router.py", line 1480, in patch_metadata
await entry.replace_metadata(
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BlueskyEventStream.replace_metadata() got an unexpected keyword argument 'drop_revision'
```
> add: replace metadata signature for BlueskyEventStream

- databroker/cli.py
Adds a parser (so that typer can cope with dictionaries) and optional argument to pass a dict as a string to be evaluated.
Root map made this unworkable for rsoxs.
- with correct json dict '{"key": "val"}'
- with incorrect dict
- with not dictionary
- with empty string
> add:  root map dict arg to cli tool to extend
