bluesky/databroker

databroker/databroker.py, databroker/tests/test_broker.py
Also hit all the error conditions in the tests
=> Verbosify error messages in databroker.py

.travis.yml, databroker/examples/sample_data/frame_generators.py
This will fix the errors that travis is spewing
=> Use pymongo 2.9 on travis

databroker/databroker.py, databroker/tests/test_broker.py
=> FIX: Time column had mismatched index.

databroker/pivot.py, databroker/tests/test_pivot.py
This converts an event stream of timeseries to an event-stream of events
with the timeseries entries 'pivoted' up to each be an event.
=> ENH: first pass at pivoting event -> event stream

databroker/__init__.py, databroker/databroker.py, databroker/tests/test_broker.py, doc/source/fetching.rst
@tacaswell and I separately needed something like this today, so it's probably a useful thing to ship with databroker.
I also added some belated docs from the `stream` function that was added earlier today.
=> Add get_fields convenience function

databroker/databroker.py
If a given field does not exist in at least one destriptor for every
header, raise.
=> MNT/API: raise if field does not exist

.travis.yml
=> CI: Unpin 3.4.3 -> 3.4.x

databroker/tests/test_broker.py
Actually prcessing the generator uncovered a few bugs! Now I need to 
squash them.
This PR will close #78 when done.
=> TST: Actually process the generators.

databroker/tests/test_broker.py
=> Test the find api with start and stop time

databroker/core.py
This change was proposed and already approved by @ericdill, @arkilic, and @klauer in #35.
=> API: No RunStop placeholder.

.travis.yml
=> CI: install FS sentinel

.travis.yml, databroker/broker.py, databroker/tests/test_examples.py
This still needs tests + relies on an un-tagged version of filestore.
=> ENH: API to get all the resource uids for a header

databroker/__init__.py, databroker/core.py, databroker/databroker.py
=> API: if config is not found, don't import DataBroker

databroker/broker.py
See docstrings for explanation. Inspired by @sbillinge and @chiahaoliu. Needs tests.
=> ENH: Add stateful 'filters' to restrict searches

.travis.yml, databroker/broker.py, databroker/core.py, databroker/tests/test_broker.py
One more instance of "maybe Ken was right," for the road.
This is WIP, needs more tests.
=> WIP: Fix stream name

doc/source/configuration.rst
There were some missing colons.
=> ENH: typos

databroker/__init__.py, databroker/broker.py, databroker/core.py, databroker/tests/test_broker.py, doc/source/searching.rst
=> Remove hard dependency on metadatastore

databroker/core.py
This will fix the error reported at [Bluesky #606](https://github.com/NSLS-II/bluesky/issues/606) when using databroker under Python 2.x.
All tests are passing locally.
Attn. @danielballan @tacaswell @licode @imrealkaren
=> FIX: Removing fullmatch which was Py3+ only.

databroker/broker.py
=> remove warning

.travis.yml, databroker/broker.py, databroker/core.py, databroker/tests/conftest.py, databroker/tests/test_broker.py, databroker/tests/test_core.py, databroker/tests/utils.py, doc/source/api_changes.rst, doc/source/design_manifesto.rst
There is more to come on this PR
=> make Headers aware of the DataBroker from whence they came

setup.py
attn @prjemian this will fix the issue you reported via email.
=> BLD: add deps to setup.py

databroker/broker.py, databroker/tests/test_broker.py
=> Export size

databroker/broker.py, databroker/core.py, databroker/handler_registration.py, databroker/tests/utils.py
This PR suppresses a number of warnings that the user can not avoid (as internally we were doing deprecated things that never were cleaned up).
=> Mnt fix warnings

databroker/broker.py, databroker/core.py, databroker/tests/test_broker.py
- eat exception in EventSourceShim layer
- move NoEventDescriptors exception from HeaderShim -> EventSourceShim
=> FIX: do not raise on no descriptors

.travis.yml
=> conda install attrs

databroker/core.py, databroker/tests/test_broker.py
Closes #173 
(Distracting myself on the Amtrak to Philly...)
=> ENH: Add convenience method for extracting config data from Descriptors

databroker/assets/core.py, databroker/assets/mongo_core.py, databroker/broker.py, databroker/core.py, databroker/eventsource/shim.py, databroker/headersource/client.py, databroker/headersource/core.py, databroker/headersource/mongo_core.py, databroker/service/metadata.py, databroker/tests/conftest.py, databroker/tests/test_broker.py, databroker/tests/test_core.py, databroker/tests/test_mds.py, databroker/tests/utils.py
=> ENH: Make the return type configurable with Broker.prepare_hook.

databroker/databroker.py, databroker/tests/test_config.py
Follow-up on #218 with more paranoid tests and a fix.
=> FIX/TST: Test that top-level functions work and warn.

databroker/__init__.py, databroker/broker.py, databroker/core.py, databroker/tests/test_broker.py, databroker/tests/test_config.py, doc/source/api.rst, doc/source/conf.py, doc/source/configuration.rst, doc/source/index.rst, doc/source/tutorial.rst, doc/source/whats_new.rst, doc/source/whats_new/v0.9.0.txt
The databroker documentation still needs a lot of love, but this
is a good start.
Also, closes #207
=> API/DOC: Some API cleanup previously discussed and new API docs

databroker/broker.py, databroker/tests/test_broker.py
=> ENH: Name the index of the DataFrame returned by get_table().

.travis.yml, databroker/assets/base_registry.py, databroker/assets/tests/test_asset.py, databroker/broker.py, setup.py
Fixes #240 and adds a text. This bug cannot be reproduced with 'develop'
installation, which is likely why it wasn't immediately caught.
Thanks for the report, @CJ-Wright.
=> FIX: Use pkg_resources correctly.

databroker/headersource/shim.py
This may fix the issue. Just need more tests. 
This is related to https://github.com/NSLS-II/databroker/issues/119
=> BUG: need to format time first on filters

databroker/tests/conftest.py
=> TST: use random port in all client/server tests

databroker/tests/test_broker.py
=> TST: update to bluesky changes

.travis.yml, setup.py
As per described in #224 - Made 'mongo' and 'hdf5' options `pip` extras.
closes #224
=> ENH: Made HDF5 and Mongo option extras.

doc/source/whats_new/v0.9.0.txt
=> DOC: Document removal of handler_override from all functions, methods.

databroker/__init__.py, databroker/_core.py, databroker/tests/test_config.py, doc/source/configuration.rst
=> ENH: Support 'description' and 'handlers' in config files.

databroker/_core.py
Some bugs caught when taking this for a test drive.
See commit messages for details.
=> FIX: Sundry databroker fixes.

databroker/_core.py, databroker/headersource/shim.py, databroker/tests/test_broker.py, doc/api-changes/db_filters.rst, doc/source/whats_new/v0.9.0.txt
We can ignore https://github.com/NSLS-II/databroker/pull/256
=> DEV: filters as dict

setup.py
I am not 100% sure I got this right. This is a reminder to follow up.
=> BLD: Make client and server deps optional.

databroker/headersource/shim.py, databroker/tests/test_broker.py
due to the issue of https://github.com/NSLS-II/databroker/issues/283
=> BUG: keep a copy of filters

databroker/assets/base_registry.py, doc/api-changes/correct_root_2016-08-15.rst, doc/source/whats_new/v0.9.0.txt
=> DOC: document correct_root

databroker/_core.py, databroker/assets/handlers.py, databroker/assets/handlers_base.py, databroker/assets/tests/test_handlers.py
This is an attempt to refactor the HDF5 handlers and add handlers for returning DASK objects
=> Refactor HDF5 handlers and add DASK handler

databroker/_core.py, databroker/tests/test_broker.py
=> FIX: DeprecatedDoct improperly warned on _repr_html_().

databroker/assets/handlers.py
very small detail but figured i'd as I go
=> added swimmer parameter doc

.travis.yml, databroker/tests/conftest.py, databroker/tests/test_broker.py, databroker/tests/test_config.py, test-requirements.txt
Not done, but want travis to spin on what is there.
=> TST: update for ophyd/bluesky version bump

.travis.yml, databroker/glue.py, databroker/tests/test_glue.py, requirements.txt, test-requirements.txt
=> ENH: first pass at creating glue Data objects from Headers

doc/source/assets.rst, doc/source/creating.rst, doc/source/index.rst
This document explains the motivation for assets and provides five nice examples of how to write a handler. It got lost in the databroker / datamuxer split more than two years ago. I have updated it to the current API.
I also did some unrelated polishing of @jrmlhermitte's new section about sentinels.
=>  DOC: Update and restore old, orphaned docs on asests and handlers.

databroker/_core.py
=> docstring fix

databroker/_core.py, databroker/assets/tests/test_fs_mutate.py, databroker/tests/test_config.py, doc/source/configuration.rst
Added `root_map` to config.
@danielballan 
I still need to review it (this was a stashed commit done earlier).
=> Added root_map to config

databroker/headersource/sqlite.py
=> PRF: make sqlite find lazy

databroker/_core.py, databroker/tests/test_broker.py, databroker/tests/test_core.py, databroker/tests/utils.py, doc/source/api.rst
- can register a (NAME, function) that takes a start and stop document and
returns an object
- payload is available on h.ext.NAME
=> ENH: add hook to also fetch external data to go with a header

doc/source/assets.rst
=> FIX: Removed extra word.

doc/source/whats_new/v0.12.0.txt
=> DOC: fix ArchiverEventSource class name

databroker/eventsource/shim.py, databroker/tests/test_broker.py
We need to cache per descriptor what fields to discard and extra data.
=> FIX: re-use of descriptor values from last descriptor for all events

doc/source/whats_new.rst, doc/source/whats_new/v0.12.1.txt
Fixed a bug in EventSourceShim.docs_given_header when filtering
fields.
=> REL: v0.12.1

doc/source/creating.rst
=> DOC: update installing sentinel code example

.codecov.yml, .travis.yml, doc/Makefile, docs-requirements.txt, test-requirements.txt
Following up on #406 chasing down more bit rot.
Closes #407
=> CI: Build on 3.7, and get docs building again.

.travis.yml, databroker/_core.py, doc/Makefile, docs-requirements.txt, requirements.txt
=> Nice yaml handling

README.md
Just updating links from NSLS-II --> bluesky
fixes #415
=> Update build badges to new bluesky org

doc/source/whats_new.rst, doc/source/whats_new/v0.13.0.txt
Summary update from v0.12.2 - v0.13.0
Drop support to Python 2
=> DOC: release

databroker/_core.py
process is a method on Broker, not a top-level function
=> DOC: fix db.process example

databroker/assets/base_registry.py, databroker/assets/sqlite.py, databroker/assets/tests/test_handlers.py
This also has a few other clean ups to account for h5py
and Python moving under us.
=> FIX: make asset registry thread safe

databroker/v1.py
This makes the `__repr__` nicer.
=> Pass name through to catalog.

.travis.yml, databroker/_core.py, databroker/_drivers/jsonl.py, databroker/_drivers/mongo_embedded.py, databroker/_drivers/mongo_normalized.py, databroker/_drivers/msgpack.py, databroker/core.py, databroker/discovery.py, databroker/in_memory.py, databroker/tests/test_broker.py, databroker/tests/test_v2/test_dask_filler.py, databroker/v1.py, databroker/v2.py, requirements.txt
Fixes for an issue found where a local databroker's to_dask() returns full numpy arrays.
=> Wip dask issue

databroker/assets/tests/test_write.py, doc/source/v2/developer/index.rst
A quick PR from vacation so I can throw out the note reminding me to fix this.
=> Phrase _drivers explanation more directly.

databroker/core.py
Fixes https://github.com/bluesky/databroker/issues/486
=> Remove a little bit of duplicate work in the BlueskyEventStream

databroker/core.py, databroker/tests/test_broker.py
Closes #491. See also #495 for explanation of rationale.
=> Make Document immutable

examples/README.md, examples/generate_mongo_data.py, examples/generate_mongo_embedded_data.py, examples/generate_msgpack_data.py
These were useful for profiling work and might be useful again.
=> Add scripts for making toy catalogs.

databroker/core.py
See https://docs.python.org/3/reference/datamodel.html#slots
=> Define __slots__ on Document.

databroker/core.py
fixes https://github.com/bluesky/databroker/issues/516
=> fix LocalCatalogEntry.get() so that a new object isn't created each time it is accessed

databroker/core.py, databroker/tests/test_v2/generic.py, databroker/v1.py
See commit messages for details. Changes relate to:
* Handling more edge cases in the test utility ``compare``
* Compatibility with v0 when the Run Stop document is missing
* Handling ragged arrays
=> Various fixes from acceptance testing

databroker/core.py, databroker/tests/test_v2/test_core.py
Fixes https://github.com/bluesky/databroker/issues/520
=> interlace fix

databroker/core.py, databroker/tests/test_document.py
~This PR is a currently just a failing test. It needs an associated fix.~
Includes fix and test. Also includes unrelated commit that makes the implementation more succinct.
=> Make Document pickle-able

databroker/core.py, databroker/tests/test_document.py
Closes #531. See that issue for discussion.
=> Give document a repr and IPython 'pretty' repr.

databroker/v2.py
This was discovered at the ALS COSMIC beamline during the integration work with @ihumphrey, @dylanmcreynolds and @tangkong.
=> Fix the handlers of the v1 temp config

databroker/assets/mongo.py, databroker/headersource/mongo.py, databroker/tests/test_config.py, databroker/v1.py
=> Allow uri's in the config file

databroker/core.py
=> Always yield event_pages from canonical

databroker/queries.py, databroker/tests/test_queries.py
The experimental `databroker.queries` module is untested. This adds tests and
some fixes.
=> Test Query objects.

databroker/v1.py
Follow-up on review comment from @mrakitin on #545
=> Use f-strings.

databroker/assets/base_registry.py, databroker/assets/mongo.py, databroker/assets/tests/test_mongo_details.py, databroker/headersource/base.py, databroker/headersource/mongo.py, databroker/v1.py
If the user account is read only, index creation fails. So in this PR indexes creation is changed so that they are made only when needed.
=> Update to support databases with authentication

databroker/__init__.py, databroker/core.py, databroker/tests/test_v2/test_core.py
Iterating on idea from https://github.com/bluesky/tutorials/blob/master/X-ray%20Absorption%20Fine%20Structure/plans.py#L15-L31
See Example section of docstring for usage.
=> Prototype SingleRunCache

databroker/_drivers/mongo_normalized.py, databroker/v1.py
Expose access to the [mongo collection statistics](https://docs.mongodb.com/manual/reference/method/db.collection.stats/).
=> Expose the mongo db.collection.stats() report

databroker/_drivers/mongo_normalized.py
Fixes https://github.com/bluesky/databroker/issues/591
=> also search for resources by _id

databroker/core.py
Passing the -1 in the shape through will result in an eventual shape
miss-match when trying to retrieve the data.  Rather than fail,
aggressively pull the data up.  The assumption is that if there were a
handler that was expected to load large volumes of data the handler
would be natively delayed.
=> FIX: if a handler is not lazy we have unknown shape don't force it

doc/source/v1/configuration.rst
Spent some time hunting this down.  Should be revealed in the documentation.
=> DOC Describe config file location on Windows

.github/workflows/docs.yml, .github/workflows/flake8.yml, .github/workflows/publish-docs.yml, .github/workflows/testing.yml, README.md, continuous_integration/scripts/install.sh, databroker/assets/tests/test_fs_mutate.py, databroker/assets/tests/test_handlers.py, docs/source/v1/tutorial.rst, requirements-docs.txt
=> Fix up GH Actions

databroker/core.py
=> Handle no stop doc in repr.

docs/source/reference/changelog.rst, docs/source/reference/changelog/v1.2.1.txt
=> v1.2.1 release notes

docs/source/reference/changelog.rst, docs/source/reference/changelog/v1.2.2.txt
=> v1.2.2 release notes

databroker/tests/test_broker.py
=> Fix the timerange tests that are failing overnight

requirements-v1.txt, setup.py
Added requirements file for v1 (`doct`, `humanize`, and `jinja2`).
Required packages weren't being picked up by pip install.
Ran a fresh `pip install -e .[complete]` and verified missing packages were present.
=> Added v1 requirements

databroker/mongo_normalized.py
=> WIP: Get columns

docs/source/explanations/v2-transition.rst
Just a documentation typo fix.
=> DOC: just a typo fix.

.github/workflows/testing.yml, databroker/intake_xarray_core/__init__.py, docs/source/how-to/store-analysis-results.rst, docs/source/how-to/store-data-from-run-engine.rst, docs/source/tutorials/export.rst, docs/source/tutorials/search-and-lookup.rst, requirements-test.txt
I've removed things that I just couldn't get working straight away:
* python3.9, seems to have problems with sqlite, i don't understand the code at all
* no longer installing intake master; i don't understand why intake tests would be run here, or why we wouldn't run the pinned version, rather than master.
Still, maybe this would be a useful place to start?
=> Hacks to get databroker github actions working

docs/source/how-to/mongo-backed-catalog.rst, requirements-test.txt
=> Doc: just fixing a few typos.

databroker/v1.py
Databroker has, up to now, mostly been used to raw data only. When we access a beamline catalog like `bmm` we implicitly mean "the _raw_ data from BMM". Going forward, we want to add a level of nesting so we can access `bmm/raw` vs `bmm/processed` or `bmm/analyzed` or whatever.
However, we want to avoid breaking
```py
Broker.named('bmm')
```
We cannot update 10000 user notebooks to `Broker.named('bmm/raw')`. This PR resolves that problem by checking to see if `bmm` has a child named `raw` and silently navigating to that if it exists.
Using old configuration (no nesting under `raw`):
```py
In [1]: from databroker import Broker
In [2]: from tiled.client import from_profile
In [3]: client = from_profile("bmm")
In [4]: client
Out[4]: <Catalog {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...} ~94098 …
```
=> Support nesting raw data into /raw in backward-compatible way.

databroker/client.py, databroker/mongo_normalized.py, databroker/queries.py, databroker/tests/conftest.py, databroker/tests/test_queries.py, databroker/v1.py, requirements-client.txt, requirements-server.txt
Closes #701 
- Updates to changes in tiled slicing
- Updates to changes in tiled query API
=> Deprecate RawMongo

databroker/experimental/server_ext.py
Minor bugfix and very minor refactor
=> Fix missing f-string f.

setup.py
Had to add tiled[minimal-client] dependency to get databroker to import.
=> add tiled dependancy

databroker/mongo_normalized.py, databroker/queries.py, databroker/tests/test_queries.py
This PR adds support for `In`, `NotIn`, and `NotEq`.
=> Support new queries types in mongo_normalized.

databroker/experimental/schemas.py, databroker/experimental/server_ext.py, databroker/mongo_normalized.py, databroker/v1.py, requirements-client.txt, requirements-server.txt
This needs https://github.com/bluesky/tiled/pull/246; the tests will not pass until that is released.
=> Update for xarray refactor in Tiled.

databroker/mongo_normalized.py
A follow-up fix on the v2.0.0b5 release. We need better test coverage on a range of handlers.
=> HOTFIX: ArrayAdapter usage with handlers that return dask.

databroker/mongo_normalized.py
This reports the width of the table correctly.
=> Implement __len__.

databroker/tests/test_temp.py
In #726 I neglected to commit the new test.
=> Follow-up to #726: commit test

databroker/v1.py
=> Header.data() fix

databroker/mongo_normalized.py, databroker/tests/test_broker.py
Closes #745
This adds a test that exercises the bug and then a fix.
=> Fix bug in config access

databroker/mongo_normalized.py, databroker/tests/test_access_policy.py, databroker/tests/test_experimental.py, databroker/tests/utils.py, databroker/v2.py, requirements-client.txt, requirements-server.txt, requirements-test.txt
Needs a Tiled release xref https://github.com/bluesky/tiled/pull/421
=> Use a more robust ALL sentinel.

requirements-client.txt, requirements-server.txt, requirements-test.txt
=> Bump tiled version.

Dockerfile, requirements-client.txt, requirements-server.txt, requirements-test.txt
The change of interest is https://github.com/bluesky/tiled/pull/426
=> Bump tiled version v0.1.0a89

databroker/experimental/server_ext.py, databroker/tests/test_experimental.py
This includes the implementation of nested `search()` queries before a `distinct()` request
=> Added distinct to MongoAdapter in experimental code

README.rst
Updates README with a corrected conda installation command.
Prompted by #776.
=> DOC: update conda installation instructions in README

Dockerfile, requirements-client.txt
Bumping Tiled base image, to get support for Awkward and to get support for a confirmation message on all Authenticators.
=> Bump base image.

databroker/mongo_normalized.py
=> Pass validate_shape through new_variation.

Dockerfile, requirements-client.txt, requirements-server.txt, requirements-test.txt
Bump minimum verison of tiled in requirements and in `Dockerfile`.
=> Bump tiled dep to v0.1.0a114

Dockerfile, requirements-client.txt, requirements-server.txt, requirements-test.txt
This is motivated only by keeping the container current.
=> Bump tiled dep to v0.1.0a115

Dockerfile, requirements-client.txt, requirements-server.txt, requirements-test.txt
Pulling in this important change https://github.com/bluesky/tiled/pull/729
=> Bump tiled to v0.1.0a120

README.rst
@ravescovi noticed the dead link following docs changes.
=> DOC: fix broken link to event-model data model

databroker/mongo_normalized.py, databroker/tests/test_broker.py, requirements-client.txt, requirements-server.txt, requirements-test.txt
https://github.com/bluesky/tiled/pull/688 depends on these changes
=> Add support for metadata patching, replacing, merging

docker-compose.yml
=> REL: v2.0.0b59

databroker/v1.py
I saw this on a dev machine. Not slowing down to investigate in detail, but I can imagine this happening given recent changes in bluesky-tiled-plugins. Can't hurt.
=> One more exception to catch

Dockerfile, databroker/mongo_normalized.py
Running CI will pick up new tiled release v0.1.0-b26.
=> Bump tiled base image

bluesky-tiled-plugins/bluesky_tiled_plugins/bluesky_run.py
Allows a user to query columns from a table in "composite" container from the `BlueskyRun` container directly, e.g.
`c[123456].v2['primary/data/det']`; `c[123456].v2['primary/data']['det']` and `c[123456].v3['streams/primary/internal/det']` always worked as expected.
=> FIX: getting columns from "composite" table
